### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by dwoffinden** [ivaniskandar/3100WatchFace#1]
Thanks for the code, really helpful!

Please note that without a license, you aren't granting permission to use, modify or share it though :(
https://choosealicense.com/no-permission#for-users

The Apache license is common for Android code? You can generate a commit to add it from https://choosealicense.com/licenses/apache-2.0

**Comment by ivaniskandar** [comment]
Thanks for the reminder! I added a license to the project.
